### PR TITLE
Added "is_" functions (à la `ctype.h`) as string methods

### PR DESCRIPTION
**Pull request by Keyaku**
- Added all but one "is_" functions (the exception being isblank())
- Updated with the appropriate documentation and comments
- Minor code and doc corrections

### CODE REVIEW

**Comment by H2CO3** [comment]
Thanks! The context parameter of the functions should be a `void *`, however. [It is declared as `void *`](https://github.com/H2CO3/Sparkling/blob/master/src/func.h#L31), so it must be `void *`, doing otherwise results in undefined behavior.

(the reason why it is a `void *` is that the extra argument can be anything, not only an SpnContext, although this opportunity is not currently used anywhere in Sparkling. In the future, it may even be removed, but for now that's how it is.

**Comment by Keyaku** [comment]
I realized that! I initially wrote `void*`, but found that one of your other aux function accepted a `SpnContext`; so I figured that the auxiliary functions would accept a `SpnContext` but the lib functions should rather take the `void*`.

**Comment by Keyaku** [comment]
I shall correct everything, then.

**Comment by H2CO3** [comment]
Yes, auxiliary functions (ones that are not directly put into the `SpnExtFunc` arrays) can (and probably should) accept an `SpnContext *` argument. They can, since `void *` is implicitly convertible to any object pointer type. So when you call a function that has a formal parameter of type `Foo *`, and the call provides an actual parameter of type `void *`, there's a conversion involved. There's no such conversion, however, when calling a function through a pointer to function of incompatible types (and implicit convertibility alone does not constitute "compatible" in the vocabulary of the C standard), so it simply becomes UB.

**Pull request merged**
