### PR TITLE
Update license to GPLv3+

### PR DESCRIPTION
**Pull request by aneeshusa**
I just heard about Sparkling and it looks really great, I'd love to start using it. However, it looks like there is a licensing problem, and I can't use it until it's been cleared up.

Currently, the code is licensed as 2-clause BSD. However, readline was added almost 2 years ago in November 2013; because readline is GPL-licensed and Sparkling links to libreadline, Sparkling also must be GPL-licensed to comply with the license. 

Readline used to be GPLv2+ licensed but is GPLv3+ licensed as of version 6.0, so I've changed the license to GPLv3+ to to comply regardless of the version of readline.

There are also some other files which ideally should get license headers, but AFAIK can be released under any license (they do not need to be GPL):
- All of the example code under examples/
- All of the tools under tools/
- The documentation under doc/ (I would suggest a documentation-specific license)

### CODE REVIEW

**Comment by H2CO3** [comment]
Hi!

First of all, thanks for your kind words and pointing out this issue. However, I really would like to avoid any forms of GPL whatsoever. The problem is real, however, and I don't want to get into a lawsuit. So, do you think it would be a viable alternative to switch to something non-GPL (e.g. [Libedit](http://thrysoee.dk/editline/), which has a 3-clause BSD license) instead?

I agree with adding licensing to the non-source files, though.

**Comment by aneeshusa** [comment]
Yes, removing readline completely and replacing it with libedit or another similarly licensed alternative should be fine. I believe for libedit you'll need to note its licensing terms in the documentation to comply with its license.

I will admit to be a bit of a GPL fan. Looking forward to using Sparkling!

**Comment by sdegutis** [comment]
:+1: for avoiding GPL software and just using BSD-licensed software like libedit (which is excellent btw).

**Comment by H2CO3** [comment]
Okay, thanks everyone for the comments. I will completely replace libreadline with libedit soon.

**Comment by H2CO3** [comment]
Switched to libedit in https://github.com/H2CO3/Sparkling/commit/8cb40826bca64ad16a0226347a7e69d10a2bd026.

**Pull request closed without merging**
